### ISSUE TITLE
Error in configuration example 

### ISSUE THREAD

**Issue by t0k4rt** [jradtilbrook/ansible-role-pgbouncer#1]
Hello,
Thanks for your ansible role :-)
I spotted a small issue in your documentation, 

This won't work:
```yaml
pgbouncer_databases:
  - dev:
      host: postgres # or the actual ip address
      port: 5432
      dbname: postgres
      user: foo
      password: md5asdofiasodfa09f9832f
```

but this will work:

```yaml
pgbouncer_databases:
  - dev:
      host: postgres # or the actual ip address
      port: 5432
      dbname: postgres
      auth_user: foo
      password: md5asdofiasodfa09f9832f
```
This small mistake is also present in your *default/main.yml* file .

The **user** key should be **auth_user**

I spent a little bit of time spotting this error in my conf :-)

Best regards
